sudo: required
dist: trusty

language: java

jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "ebolon"
    token:
      secure: $SONAR_TOKEN

before_script:
  - cd ..
  - git clone https://github.com/eclipse/vorto.git
  - cd vorto
  - mvn clean install -f pom.xml
  - cd ..
  - cd vorto-eclipse-plugin
 
before_install: echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

install: true
script:
  - mvn -B -q clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
